//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace raylight.api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("raylight.api.Resources.IdentityResources", typeof(IdentityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password failed.
        /// </summary>
        public static string ChangePasswordFailed 
        {
            get 
            {
                return ResourceManager.GetString("ChangePasswordFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Login.
        /// </summary>
        public static string InvalidLogin
        {
            get
            {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string InvalidPassword
        {
            get
            {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidToken
        {
            get
            {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        public static string InvalidUser
        {
            get
            {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code.
        /// </summary>
        public static string InvalidVerificationCode
        {
            get
            {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LoginFailed
        {
            get
            {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh Failed.
        /// </summary>
        public static string RefreshFailed
        {
            get
            {
                return ResourceManager.GetString("RefreshFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration Error.
        /// </summary>
        public static string RegistrationError
        {
            get
            {
                return ResourceManager.GetString("RegistrationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request Invalid.
        /// </summary>
        public static string RequestInvalid
        {
            get
            {
                return ResourceManager.GetString("RequestInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Token expired.
        /// </summary>
        public static string TokenExpired
        {
            get
            {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Token not found.
        /// </summary>
        public static string TokenNotFound
        {
            get
            {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Token dont match.
        /// </summary>
        public static string TokenNotMatched
        {
            get
            {
                return ResourceManager.GetString("TokenNotMatched", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Token is revoked.
        /// </summary>
        public static string TokenRevoked
        {
            get
            {
                return ResourceManager.GetString("TokenRevoked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UnknownError
        {
            get
            {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User already exist.
        /// </summary>
        public static string UserAlreadyExist
        {
            get
            {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
    }
}