<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>RaylightApi.Presentation</RootNamespace>
		<AssemblyName>RaylightApi.Presentation</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
	</ItemGroup>

</Project>
