name: 'Deploy Application'
description: 'Deploy Application'
runs:
  using: "composite"
  steps:

    - name: Deploy Solution
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ env.PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}