name: Unit Test, Build and Publish (raylight-api)

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: raylight-api
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  RAYLIGHT_API_APP_SETTINGS: ${{ secrets.RAYLIGHT_API_APP_SETTINGS }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      
      - name: Configuration and Setup
        uses: ./.github/actions/setup-action

      - name: Unit Test
        uses: ./.github/actions/unit-test-action

      - name: Build and Publish
        uses: ./.github/actions/build-action

      - name: Deploy
        uses: ./.github/actions/deploy-action